linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gochecknoglobals
linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
issues:
  exclude:
    - composites
run:
  tests: false