version: 2.1

executors:
  my-executor:
    environment: 
      IMAGE_NAME: vladwoode/social-tournament-service
    docker:
      - image: circleci/golang:1.12
        environment:
          - GO111MODULE=on
    working_directory: /go/src/github.com/HarlamovBuldog/social-tournament-service

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: go build -mod=vendor ./...
  test:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/go/src/github.com/HarlamovBuldog/social-tournament-service
    steps:
      - run:
          name: Update Go to 1.12.6
          working_directory: /tmp
          command: |-
            wget https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.12.6.linux-amd64.tar.gz
      - checkout
      - run: env GO111MODULE=on go test -mod=vendor -v -cover ./...
  create-push-docker-image:
    executor: my-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2.1
  build-test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - create-push-docker-image:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
